os: linux
sudo: required
language: "minimal"
services:
  - docker

before_script:
  - docker pull toliak/bootstrap-cpp

jobs:
  include:
    - name: "tests"
      script:
        - docker run -t -v $(pwd):/opt/builder/ --entrypoint ./scripts/tests.sh toliak/bootstrap-cpp



notifications:
  email: false

